#!/usr/bin/env python3

import argparse
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler

def main():
    parser = argparse.ArgumentParser(description="Out-of-Core Correctness Check")
    parser.add_argument("--input", type=str, required=True, help="Original input binary file")
    parser.add_argument("--output", type=str, required=True, help="Output binary file generated by C program")
    parser.add_argument("--samples", type=int, required=True, help="Number of samples (N)")
    parser.add_argument("--features", type=int, required=True, help="Number of features (D)")
    parser.add_argument("--mode", type=str, required=True, choices=["standard", "minmax"], help="Scaling mode used")
    parser.add_argument("--chunk-size", type=int, default=100000, help="Rows per chunk to avoid OOM")
    
    args = parser.parse_args()

    print(f"Checking correctness for N={args.samples}, D={args.features}, Mode={args.mode}")

    if args.mode == "standard":
        scaler = StandardScaler()
    else:
        scaler = MinMaxScaler()

    # ΦΑΣΗ 1: Υπολογισμός στατιστικών με partial_fit για να μη γεμίσει η RAM
    print("Phase 1: Calculating scikit-learn reference statistics (Chunked)...")
    with open(args.input, "rb") as f_in:
        rows_processed = 0
        while rows_processed < args.samples:
            current_chunk = min(args.chunk_size, args.samples - rows_processed)
            chunk_data = np.fromfile(f_in, dtype=np.float64, count=current_chunk * args.features)
            if chunk_data.size == 0:
                break
            chunk_data = chunk_data.reshape((current_chunk, args.features))
            
            scaler.partial_fit(chunk_data)
            rows_processed += current_chunk

    # ΦΑΣΗ 2: Σύγκριση τμηματικά (Chunk-by-Chunk) για αποφυγή OOM
    print("Phase 2: Computing max and mean absolute errors...")
    max_error = 0.0
    sum_error = 0.0
    total_elements = args.samples * args.features

    with open(args.input, "rb") as f_in, open(args.output, "rb") as f_out:
        rows_processed = 0
        while rows_processed < args.samples:
            current_chunk = min(args.chunk_size, args.samples - rows_processed)
            elements_to_read = current_chunk * args.features

            chunk_in = np.fromfile(f_in, dtype=np.float64, count=elements_to_read).reshape((current_chunk, args.features))
            chunk_c_out = np.fromfile(f_out, dtype=np.float64, count=elements_to_read).reshape((current_chunk, args.features))

            chunk_expected = scaler.transform(chunk_in)

            abs_errors = np.abs(chunk_expected - chunk_c_out)
            chunk_max = np.max(abs_errors)
            chunk_sum = np.sum(abs_errors)

            if chunk_max > max_error:
                max_error = chunk_max
            sum_error += chunk_sum

            rows_processed += current_chunk

    mean_error = sum_error / total_elements

    print("\n=== RESULTS ===")
    print(f"Max Absolute Error:  {max_error:.10e}")
    print(f"Mean Absolute Error: {mean_error:.10e}")

    tolerance = 1e-9
    if max_error < tolerance:
        print("\nSUCCESS: The C implementation matches scikit-learn perfectly!")
    else:
        print("\nWARNING: High error detected. Please check the implementation.")

if __name__ == "__main__":
    main()